[package]
name = "sval_buffer_bench"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies.sval]
path = "../../"
features = ["std"]

[dependencies.sval_buffer]
path = "../"
features = ["std"]

[dependencies.sval_derive_macros]
path = "../../derive_macros"

[dependencies.criterion]
version = "0.8"

[[bench]]
name = "value"
path = "value.rs"
harness = false
