[package]
name = "sval_json_twitter_benches"
version = "0.0.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies.sval]
path = "../../../"
features = ["derive", "serde", "std"]

[dependencies.sval_json]
path = "../../"
features = ["std"]

[dependencies.sval_json_twitter_tests]
path = "../../tests/twitter"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serde_json]
version = "1"

[dependencies.miniserde]
version = "0.1"

[dependencies.erased-serde]
version = "0.3"
