[package]
name = "sval_ref"
version = "2.0.3"
edition = "2021"

[features]
std = ["alloc", "sval/std"]
alloc = ["sval/alloc"]

[dependencies.sval]
version = "2.0.3"
path = "../"

[dev-dependencies.sval_test]
version = "2.0.3"
path = "../test"
